---
name: Docker
inputs:
  context:
    required: true
    type: string
  args:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Ensure docker context exists
      run: docker context create buildx || docker context use buildx
      shell: bash

    - name: Setup buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0
        endpoint: buildx

    - name: Build dockerfile
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ${{ inputs.context }}
        tags: cargo
        load: true
        push: false
        cache-from: type=local,src=/tmp/buildx-cache
        cache-to: type=local,dest=/tmp/buildx-cache

    - name: Run
      run: |
        cat $GITHUB_ENV
        docker run --rm \
            \
            -e DOCKER_CACHE_DIR \
            -e DOCKER_CACHE_FILE \
            -e INPUT_ARGS \
            -e HOME \
            -e GITHUB_JOB \
            -e GITHUB_REF \
            -e GITHUB_SHA \
            -e GITHUB_REPOSITORY \
            -e GITHUB_REPOSITORY_OWNER \
            -e GITHUB_RUN_ID \
            -e GITHUB_RUN_NUMBER \
            -e GITHUB_RETENTION_DAYS \
            -e GITHUB_RUN_ATTEMPT \
            -e GITHUB_ACTOR \
            -e GITHUB_WORKFLOW \
            -e GITHUB_HEAD_REF \
            -e GITHUB_BASE_REF \
            -e GITHUB_EVENT_NAME \
            -e GITHUB_SERVER_URL \
            -e GITHUB_API_URL \
            -e GITHUB_GRAPHQL_URL \
            -e GITHUB_REF_NAME \
            -e GITHUB_REF_PROTECTED \
            -e GITHUB_REF_TYPE \
            -e GITHUB_WORKSPACE \
            -e GITHUB_ACTION \
            -e GITHUB_EVENT_PATH \
            -e GITHUB_ACTION_REPOSITORY \
            -e GITHUB_ACTION_REF \
            -e GITHUB_PATH \
            -e GITHUB_ENV \
            -e RUNNER_OS \
            -e RUNNER_ARCH \
            -e RUNNER_NAME \
            -e RUNNER_TOOL_CACHE \
            -e RUNNER_TEMP \
            -e RUNNER_WORKSPACE \
            -e ACTIONS_RUNTIME_URL \
            -e ACTIONS_RUNTIME_TOKEN \
            -e ACTIONS_CACHE_URL \
            -e GITHUB_ACTIONS=true \
            -e CI=true \
            \
            -v "/var/run/docker.sock":"/var/run/docker.sock" \
            -v "$RUNNER_TEMP/_github_home":"/github/home" \
            -v "$RUNNER_TEMP/_github_workflow":"/github/workflow" \
            -v "$RUNNER_TEMP/_runner_file_commands":"/github/file_commands" \
            -v "$RUNNER_WORKSPACE":"/github/workspace" \
            \
            -w /github/workspace \
            \
            --entrypoint=ls \
            \
            cargo -lha
      shell: bash

    - name: Run
      run: |
        docker run --rm \
            \
            -e DOCKER_CACHE_DIR \
            -e DOCKER_CACHE_FILE \
            -e INPUT_ARGS \
            -e HOME \
            -e GITHUB_JOB \
            -e GITHUB_REF \
            -e GITHUB_SHA \
            -e GITHUB_REPOSITORY \
            -e GITHUB_REPOSITORY_OWNER \
            -e GITHUB_RUN_ID \
            -e GITHUB_RUN_NUMBER \
            -e GITHUB_RETENTION_DAYS \
            -e GITHUB_RUN_ATTEMPT \
            -e GITHUB_ACTOR \
            -e GITHUB_WORKFLOW \
            -e GITHUB_HEAD_REF \
            -e GITHUB_BASE_REF \
            -e GITHUB_EVENT_NAME \
            -e GITHUB_SERVER_URL \
            -e GITHUB_API_URL \
            -e GITHUB_GRAPHQL_URL \
            -e GITHUB_REF_NAME \
            -e GITHUB_REF_PROTECTED \
            -e GITHUB_REF_TYPE \
            -e GITHUB_WORKSPACE \
            -e GITHUB_ACTION \
            -e GITHUB_EVENT_PATH \
            -e GITHUB_ACTION_REPOSITORY \
            -e GITHUB_ACTION_REF \
            -e GITHUB_PATH \
            -e GITHUB_ENV \
            -e RUNNER_OS \
            -e RUNNER_ARCH \
            -e RUNNER_NAME \
            -e RUNNER_TOOL_CACHE \
            -e RUNNER_TEMP \
            -e RUNNER_WORKSPACE \
            -e ACTIONS_RUNTIME_URL \
            -e ACTIONS_RUNTIME_TOKEN \
            -e ACTIONS_CACHE_URL \
            -e GITHUB_ACTIONS=true \
            -e CI=true \
            \
            -v "/var/run/docker.sock":"/var/run/docker.sock" \
            -v "$RUNNER_TEMP/_github_home":"/github/home" \
            -v "$RUNNER_TEMP/_github_workflow":"/github/workflow" \
            -v "$RUNNER_TEMP/_runner_file_commands":"/github/file_commands" \
            -v "$GITHUB_WORKSPACE":"/github/workspace" \
            \
            -w /github/workspace \
            \
            cargo ${{ inputs.args }}
      shell: bash
