---
name: Cargo
description: Rust | Run cargo
inputs:
  args:
    description: Arguments for cargo
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - uses: r7a1/i3utils/.github/actions/docker@master
      with:
        file: ./Dockerfile
        args: ${{ inputs.args }}
