---
name: Cargo
description: Rust | Run cargo
inputs:
  args:
    description: Arguments for cargo
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - uses: ./.github/actions/docker
      with:
        context: ./.github/actions/cargo
        args: ${{ inputs.args }}
