---
name: Build
on:
  workflow_dispatch:
env:
  DOCKER_CACHE_DIR: /tmp/docker-cache
  DOCKER_CACHE_FILE: snapshot.tar
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Enable docker cache
        id: docker-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}
          key: ${{ hashFiles('./.github/actions/cargo/Dockerfile') }}

      - name: Load docker cache if it exists
        if: steps.docker-cache.outputs.cache-hit == 'true'
        run: docker load --input ${{ env.DOCKER_CACHE_DIR }}/${{ env.DOCKER_CACHE_FILE }} || true

      - name: Build docker file
        uses: ./.github/actions/cargo
        with:
          args: --version

      - name: Save docker cache
        run: |
          mkdir -p ${{ env.DOCKER_CACHE_DIR }}
          docker save $(docker images -q) --output ${{ env.DOCKER_CACHE_DIR }}/${{ env.DOCKER_CACHE_FILE }}

      - name: Enable rust cargo cache
        uses: actions/cache@v2
        with:
          path: |
            /opt/rust/registry
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build and Test
        uses: ./.github/actions/cargo
        with:
          args: test

      - name: Build RPM Package
        uses: ./.github/actions/cargo
        with:
          args: rpm build

      - name: Upload RPM Package
        uses: actions/upload-artifact@v2
        with:
          name: i3utils.rpm
          path: target/release/rpmbuild/RPMS/x86_64/*.rpm
