---
name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cargo
        with:
          args: test
      - uses: ./.github/actions/cargo
        with:
          args: rpm
      - uses: actions/upload-artifact@v2
        with:
          name: i3utils.rpm
          path: target/release/rpmbuild/RPMs/x86_64/*.rpm
