---
name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Enable rust cargo cache
        uses: actions/cache@v2
        with:
          path: |
            /opt/rust/registry
            /opt/rust/sccache
            target
          key: cargo-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            cargo-${{ github.ref }}-

      - name: Build and Test
        uses: ./.github/actions/cargo
        with:
          args: test

      - name: Build RPM Package
        uses: ./.github/actions/cargo
        with:
          args: rpm build

      - name: Upload RPM Package
        uses: actions/upload-artifact@v2
        with:
          name: i3utils.rpm
          path: target/release/rpmbuild/RPMS/x86_64/*.rpm
